---
title: "작업방법 및 시간연구"
format: html
---

## 동작경제원칙

**동작경제원칙**(Principle of motion economy)은 <font color="blue">작업 효율성을 향상시키기 위해 인간 동작을 최소화하고 최적화하는 원칙</font>이다. 주로 산업공학, 작업설계 및 생산성 향상 분야에서 사용되며 사람 동작을 더 빠르고 효율적으로 만들기 위해 다양한 기술적, 물리적 방법을 제시한다.

이 원칙은 **Frank B. Gilbreth와 Lillina M. Gilbreth 부부**가 20세기 초에 개발한 **동작연구(Motion study)에서 유래**했다. <font color="blue">사람 동작을 분석하고 불필요한 동작을 제거함으로써 작업 효율을 높이고 피로도를 줄이며 생산성을 향상시키는 방법</font>을 제시했다.

동작경제원칙 핵심 요소
:   - **동작 간소화**  
      동작을 수행하는데 필요한 동작 수를 줄인다. 즉 한번에 두개 이상 동작을 동시에 하거나 불필요한 동작을 피할 수 있도록 설계한다.
    - **동작 효율성**  
      동작은 최대한 자연스럽고 효율적으로 이루어져야 하며, 불필요하게 힘을 주거나 긴 시간을 소요하는 동작은 피해야 한다.
    - **동작 표준화**  
      사람마다 작업 동작에 차이가 있을 수 있는데, 가장 효율적으로 표준화된 동작 방법을 설정하여 모든 작업자가 동일한 방식으로 작업을 수행하게 한다.
    - **동작 순서화**  
      작업을 할 대 동작 순서를 논리적이고 일관되게 배치하여 작업자가 불필요하게 멈추거나 돌아가지 않도록 한다.
    - **도구와 장비 최적화**  
      작업에 필요한 도구와 장비는 손쉽게 접근할 수 있도록 배치하며, 불필요한 움직임을 최소화하는 디자인을 적용한다.

동작경제원칙 장점
:   - **생산성 향상**  
      불필요한 동작을 줄이고 효율적인 작업 흐름을 만들어 생산성을 높일 수 있다.
    - **피로감 감소**  
      불필요한 움직임을 최소화하면 작업자 피로도가 줄어들어 더 우래 작업이 가능하다.
    - **비용 절감**  
      작업 시간이 단축되고, 인력 효율성이 높아져 인건비나 운영 비용이 절감될 수 있다.
    - **안전성 향상**  
      효율적인 동작 설계를 통해 작업 중 사고나 부상 위험을 줄일 수 있다.

F.B. Gilbreth가 처음 사용하고 **반즈(R.M. Banrnes)가 개량 보완한 동작경제 3원칙**은 다음과 같다.

동작경제 3원칙
: 1. <font color="blue">신체 사용에 관한 원칙</font>
  2. 작업역 배치에 관한 원칙
  3. 공구 및 설비 설계에 관한 원칙


:::{.callout-tip icon=false title="기출: 109-1-2"}
:::

<font color="blue">신체 사용에 관한 원칙</font>
:   1. 양손은 동시에 동작을 시작하고 또 끝마쳐야 한다.
    2. 휴식시간 이외에 양손이 동시에 노는 시간이 있어서는 안 된다.
    3. 양팔은 각기 반대방향에서 대칭적으로 동시에 움직여야 한다.
    4. 손의 동작은 작업을 수행할 수 있는 최소동작 이상을 해서는 안 된다.
    5. 작업자들을 돕기 위하여 동작의 관성을 이용하여 작업하는 것이 좋다.
    6. 구속되거나 제한된 동작 또는 급격한 방향전환보다는 유연한 동작이 좋다.
    7. 작업동작은 율동이 맞아야 한다.
    8. 직선동작보다는 연속적인 곡선동작을 취하는 것이 좋다.
    9. 탄도동작(ballistic movement)은 제한되거나 통제된 동작보다 더 신속, 정확, 용이하다.
    10. 눈을 주시시키는 동작 또는 이동시키는 동작은 되도록 적게 하여야 한다.

작업역 배치에 관한 원칙
:   1. 모든 공구와 재료는 일정한 위치에 정돈되어야 한다.
    2. 공구와 재료는 작업이 용이하도록 작업자의 주위에 있어야 한다.
    3. 재료를 될 수 있는 대로 사용위치 가까이에 공급할 수 있도록 중력을 이용한 호퍼 및 용기를 사용하여야 한다.
    4. 가능하면 낙하시키는 방법을 이용하여야 한다.
    5. 공구 및 재료는 동작에 가장 편리한 순서로 배치하여야 한다.
    6. 채광 및 조명장치를 잘 하여야 한다.
    7. 의자와 작업대의 모양과 높이는 각 작업자에게 알맞도록 설계되어야 한다.
    8. 작업자가 좋은 자세를 취할 수 있는 모양, 높이의 의자를 지급해야 한다.

공구 및 설비 설계에 관한 원칙
:   1. 치구, 고정장치나 발을 사용함으로써 손의 작업을 보존하고 손은 다른 동작을 담당하도록 하면 편리하다.
    2. 공구류는 될 수 있는 대로 두 가지 이상의 기능을 조합한 것을 사용하여야 한다.
    3. 공구류 및 재료는 될 수 있는 대로 다음에  사용하기 쉽도록 놓아 두어야 한다.
    4. 각 손가락이 사용되는 작업에서는 각 손가락의 힘이 같지 않음을 고려하여야 할 것이다.
    5. 각종 손잡이는 손에 가장 알맞게 고안함으로써 피로를 감소시킬 수 있다.
    6. 각종 레버나 핸들은 작업자가 최소의 움직임으로 사용할 수 있는 위치에 있어야 한다.
  

## 작업시간 산정

작업시간을 산정하는 방법에는 통계적인 방법, 관측을 통한 방법, 그리고 기존 자료를 활용한 합성법이 있다.

```{mermaid}
flowchart LR
00[작업시간 산정]
01[통계적 방법]
02[관측법]
03[합성법]

subgraph s01[" "]
11[경험 견적법]
12[실적 자료법]
end

subgraph s02[" "]
21[직접 관측법]
211["**시간연구법(Stop watch)**"]
212["**작업표본 분석법<br>(Work sampling)**"]
22[간접 관측법]
221[미세동작 연구법]
222[동작궤적 분석법]
end

subgraph s03[" "]
31["**기정시간 표준법<br>(PTS)**"]
311["**작업요소시간 표준법<br>(Work factor)**"]
312["방법시간 표준법(MTM)"] --- 혼다
32[표준시간 자료법] ---- D
313["**MODAPTS**"] --- D[도요다]
321["컴퓨터 시뮬레이션 기법(CAPES)"]
end

00 --- 01 & 02 & 03

01 --- 11 & 12

02 --- 21 --- 211 & 212
02 --- 22 --- 221 & 222

03 --- 31 --- 311 & 312 & 313
03 --- 32 --- 321

```

### 직접 관측법

작업자를 직접 관측하여 표준 시간을 산정하는 방식이다. 대표적으로 **시간연구법**과 **워크 샘플링법**이 있다.

#### 시간연구법 {#sec-time-study}

**시간연구법**(Time study)은 19세기말 Frederick Winslow **Taylor**가 공식 도입한 방법으로 어떤 업무를 <font color="blue">한 작업자가 여러 번 수행하는 것을 관찰하여 표준시간을 정하는 방식</font>이다.

절차
:   1. **연구대상 업무를 설정**하고 그것을 수행할 작업자에게 알림
    1. 관찰 **횟수**를 결정
    1. 시간을 **측정**하고 그 작업자 성과를 **평가**
    1. **표준시간**을 계산

선정된 작업자가 작업시간을 늘리려고 불필요한 동작을 하는 경우가 많기 때문에 연구를 수행하는 분석 담당자는 대상 업무를 철저히 알고 있어야 하며, 표준시간을 정하기 이전에 그 업무가 효율적으로 수행되는지 확인할 필요가 있다. 측정횟수는 관측된 시간 변동성, 정확도 목표, 추정된 업무시간 신뢰도 수준 목표에 맞게 설정한다.

$$
측정횟수(n) = (\frac{zs}{a\bar{x}})^2
$$ {#eq-time-study-n}

여기서,  

- $z$ = 목표 신뢰도를 달성하기 위한 표준편차(**신뢰도 목표**)
- $s$ = 표본 **표준편차**
- $a$ = **정확도 목표**
- $\bar{x}$ = **표본평균**

:::{.callout-important icon=false title="시간연구법"}
평균시간 6.4분, 표준편차 2.1분, 신뢰도 목표 95%, 표본평균 ±10%일 때, 측정횟수를 계산하시오.

----

신뢰도 목표 95%에서 $z$ 값이 1.96이므로 아래와 같이 측정횟수를 계산할 수 있다(@eq-time-study-n).

$$
측정횟수(n) = (\frac{zs}{a\bar{x}})^2 = (\frac{1.96 \times 2.1}{0.1 \times 6.4})^2 = 41.36
$$

:::

#### 워크 샘플링 {#sec-work-sampling}

**워크샘플링**(work sampling)법은 <font color="blue">확률을 기반으로 최소한 샘플을 순간적으로 관측하여, 관측 대상으로 하는 현장 전체 모습을 실용상 만족할 만한 신뢰구간과 정확도를 가지고 추정하는 작업측정 기법</font>이다.

| **구분** | **장점** | **단점** |
|---------|---------|---------|
| **훈련 및 비용** | 실시 절차가 복잡하지 않아 고도 훈련이 필요 없음 | 작업을 요소별로 분할해 관측할 수 없음 |
| **비용** | 시간 연구법에 비해 비용이 저렴함 | 관측 결과의 오차가 시간 연구법보다 큼 |
| **심리적 영향** | 작업자에게 심리적 압박을 배제할 수 있음 | |  
: 작업 관측법의 장단점 {tbl-colwidths="[10,50,40]"}

작업 관측법은 <font color="blue">간단한 절차와 낮은 비용</font>, 그리고 <font color="blue">작업자의 심리적 부담 감소</font>라는 장점을 가지지만, <font color="red">세부 분석 부족 및 오차 발생 가능성</font>이 단점으로 지적된다.

워크샘플 표준시간 선정 절차
:   1. 관측 대상과 목적을 정한다.
    2. 특정 활동 발생률(유휴율 내지 가동률)을 추정한다.
    3. 관측에서 요구되는 신뢰수준과 정확도(오차율)를 정한다.
    4. 관측이 행해질 관측시간을 랜덤으로 정한다.
    5. 조사기간 중 두세 차례에 걸쳐 필요한 관측 수를 재계산하여 조정한다.
    6. 관측겨로가에 의해서 정상시간과 표준시간을 산성한다.

워크샘플링 표준시간 계산 방법
: 1. 관측수(N) 결정  
    $$N = (\frac{K}{S})^2\frac{1-p}{p}$$ {#eq-work-sampling-n}  

여기서  
- N: 랜덤 관측 횟수(샘플 크기)
- K: 신뢰수준에 따라 정해지는 표준편차 배수
- S: p에 대한 상대적 정도(허용오차)
- p: 구하는 비율(발생률)  

  2. 표준시간 산정  
    $$정상시간(단위당)=\frac{\text{총관측시간 x 발생률 x 수행도평가(레이팅)}}{생산량}$$ {#eq-work-sampling-st}

여기서 여유시간을 가산하여 단위당 표준시간 산정  
- 표준시간 = 정상시간(1+여유률) 또는 정상시간 x $(\frac{1}{1-여유율})$

워크샘플링 적용 대상  
:   - 시간연구법으로 적용하기 어려운 비반복적인 업무에 효과적
    - 기계수리, 세탁, 토목공사 등과 같은 업무에 활용


### PTS {#sec-pts}

::: {.callout-tip icon=false title="기출: 109-2-2"}
:::

**PTS**(predetermined time standard)는 <font color="blue">이미 작성된 작업요소들을 이용하여 표준시간을 계산하는 방식</font>이다. 1940년대 말 Method Engineering Council이 개발한 방법시간측정(MTM, Methods-time measurement)을 주로 사용했다.

```{mermaid}
flowchart LR
MTA --- WF --- MTM --- BMT --- RWF --- MODAPTS
```

PTS 발전
: - 1942년 MTA(Motion time study)라는 명칭으로 처음 소개된 이래 다양한 기법이 연구됨
- `MTA`, Motion time Analysis 1924
- `WF`, Work factor 1938
- `MTM`, Method time measurement 1948
- `BMT`, Basic motion time study 1950
- `RWF`, Ready work factor
- `MODAPTS`, Modular arrangement of predetermined time standards 1966

| **장점**                                                                 | **단점**                                                                 |
|--------------------------------------------------------------------------|--------------------------------------------------------------------------|
| **간접 측정방법으로 작업자 불편 제거**                                          | **회사 설정에 가장 적합한 PTS 시스템 선택이 곤란**                           |
| 스톱워치 미사용으로 별도 레이팅 불필요                                      | 시스템에 내재된 표준 페이스를 고려한 시간치 조정 단계 필요 (인종, 연령, 성별 고려치 않아 실제 오차 존재) |
| 생산 시작 전 사전 시간 산출 및 견적이 가능                                | 도입 초기 PTS 전문가 자문 필요                                          |
| 시간 연구자가 각 동작을 세밀히 분석함으로 더 나은 작업 방법을 자동적으로 제안 가능 | 시스템 활용을 위한 교육 및 훈련 비용 발생                               |
| 작업 방법에 대한 매우 자세한 기록이 남아 작업자 훈련과 작업 방법 변동 요인을 찾기가 용이 | 기계적으로 제어되는 동작시간에 적용 불가                                |
| 표준시간 산정을 위한 공수 감소, 표준자료 작성 용이                        |                                                                          |

주요 기법 비교 내용이다.

구분|정의|개발배경|복잡성/난이도|시간단위|Pace|정밀도/적용
-|-|-|-|-|-|-
WF|신체 각 부분 동작 난이도에 다라 서로 다른 개수로 work factor 부여|DWF 1945|복잡/쉬움|1RU(Ready time unit) = 0.001분|Incentive pace 125% rate|전자 및 기계조립 업체
MTM|작업에 필요한 기본 동작으로 분해하고 성질과 조건에 대응하는 시간치 부여|MTM1 1948, MTM2 1965, MTM3 1971| 간단, 약간 어려움|1TMU(Time measurement unit) = (1/100000)시간|Normal pace 100% rate|중공업
MODAPTS|신체 각 부분 동작 거리에 따라 시간치를 부여|Basic M 1966, Offixe M 1969, Tmnit M 1973|매우간단, 쉬움|1MOD(Modular) = 0.129/0.1초, 0.143/0.12초|4가지 pace임의로 채용|정밀기계, 가공업체

#### WF {#sec-work-factor}

:::{.callout-tip icon=false title="기출: 103-3-1, 127-1-12"} 
:::

**WF**(Work factor)법은 각 신체 부위마다 움직이는 거리, 취급중량, 작업자에 의한 제어 여부(동작 곤란) 등과 같은 변수에 대해 각 동작시간 표준치를 정하여 동작시간 표준을 적용하여 실질 시간을 구하는 기법이다. 인간이 하는 작업에는 그 작업 구성요소인 동작을 행하는 신체부위, 동작 크기, 동작 제약 외적 조건에 따라 동작 수행에 소요되는 객관적으로 적정한 시간이 존재한다는 전제에서 측정한다. 따라서 각 요소 동작마다 각 신체 부위별로 동작시간을 실제 데이터에 의해 제약요인과 관렩지어 해석하고 시간표를 만들어 둔다. 측정 단위 시간은 WFU며, 1분 = 10,000WFU이다.

기본원리
: 
- 모든 작업 동작은 제한된 몇가지 기본 요소 동작으로 분해 가능
- 각각 기본 요소 동작은 일정한 표준 시간치를 가짐
- 작업 동작 총 소요시간은 기본 요소 동작에 대한 표준 시간 합계 시간이 됨

4가지 주요 변수(시간 변동 요인)
: 
- 사용되는 신체부위
        - 손가락(F), 손(H), 앞팔선희(F8), 팔(A), 몸통(T), 다리(L), 발(FT), 머리회전(HT)
- 이동 거리
        - 1~100cm, 45~180도
- 중량 또는 저항
        - 저항이 커질수록 W -> WW -> WWW, 신체 부위별 W 계수 다름
- **동작 곤란성**
        - 일정한 정지(D), 방향 조절(S), 주의(P), 방향변경(U)

번호|표준요소|기호|동작내용
-|-|-|-
1-1|이동-뻗치다|R|손이나 팔 등 신체부위 위치를 바꿈
1-2|이동-옮긴다|M|물건을 이동시킴(또는 이동중에 유용한 이을 함)
2|잡는다|Gr|물체를 작업자 컨트롤하에 두는 동작
3|놓는다|RI|물체에서 신체부위를 분리하는 동작
4|앞에 놓다|PP|다음 목적에 알맞게 물체 방향을 바꾸는 동작
5|조립|Asy|2가지 물체를 조합 또는 정리하는 동작
6|사용|Use|공구 및 기계 등을사용하는 요소
7|분해|Dsy|조립된 물체를 풀어내는 동작
8|정신작용|Mp|눈, 귀, 뇌 및 신경계통을 사용하는 요소
9|대기|W|대기, 놓고 있는 상태
10|유지|H|물건을 들고 있거나 누르고 있는 상태

```{mermaid}
flowchart TB
00[WF 동작시간 표준] --- 01[WF 동작분석]
01 --- 기초동작 & WF
기초동작 --- 11[사용되는 신체부위] & 12[이동거리] & 13[동작 또는 저항] & 14[동작 곤란성]
01 --- 기초동작 & WF
WF --- 11[사용되는 신체부위] & 12[이동거리] & 13[동작 또는 저항] & 14[동작 곤란성]
```

사용방법
: 
- 표준요소 10가지로 구분 실시
- 구분된 표준 요서별로 사용 신체 부위, 이동거리, 중량 또는 저항과 동작 곤란성 요소를 조사하여 WF(W, S, P, U, D 순으로) 기록

WF법의 표준시간의 설정절차
: 
1. 필요한 모든 정보를 수집한다. 
1. 작업을 단위 또는 요소작업으로 분할한다.
1. 단위작업을 기본동작으로 구분한다.
1. 각 동작에 데이터를 적용하여 정미시간을 산출한다.
1. 여유율을 산정한다.
1. 표준시간을 결정한다

#### MODAPTS {#sec-modapts}

`MODAPTS`(Modular Arrangement of Predetermined Time Standards) 시스템은 작업자의 신체 동작을 분석하여 작업 시간을 측정하고 표준을 설정하는 방법이다. MODAPTS에서 신체 동작은 여러 기본 단위로 나누어지며, 주요 동작 3가지는 다음과 같다.

1. **Reach (리치)**:
   - **설명**: 작업자가 물체를 잡기 위해 팔을 뻗는 동작입니다. 이 동작은 작업자가 물체를 가져오기 위해 팔을 앞으로 뻗을 때의 시간을 측정하는 데 사용된다.
   - **예시**: 작업자가 테이블 위의 물건을 집기 위해 팔을 뻗을 때의 동작.

2. **Grasp (그랩)**:
   - **설명**: 물체를 손으로 잡는 동작입니다. 이 동작은 물체를 손으로 쥐는 데 소요되는 시간을 측정한다.
   - **예시**: 작업자가 도구를 손에 쥐거나 물건을 집을 때의 동작.

3. **Move (무브)**:
   - **설명**: 물체를 이동시키는 동작입니다. 이는 물체를 한 장소에서 다른 장소로 옮기는 데 드는 시간을 측정한다.
   - **예시**: 작업자가 물건을 한 곳에서 다른 곳으로 옮기는 동작.

## 학습곡선 {#sec-learning-curve}

::: {.callout-tip icon=false title="기출: 109-2-3, 112-1-2, 118-1-9"} 
:::

작업을 반복함에 따라 작업 소요시간 즉, 공수(Man hour)가 체감되는데, 이와 같은 현상을 공수 체감 현상이라고 한다. 이 공수 체감 현상 내지 능률 개선율을 그래프나 수식으로 나타낸 것을 **학습곡선**(Learning curve)이라고 한다. 학습현상 혹은 학습효과란 동일한 업무를 반복적으로 수행함에 따라 숙련도가 증가되어 단위당 작업시간이 감소하여 단위당 원가가 감소하는 현상을 말한다.

**학습효과**는 <font color="blue">생산량이 2배 증가함에 따른 단위당 노동시간 감소를 뜻</font>하며, 학습률이 80%라면 학습효과는 20%가 된다. 즉, 첫 번째 단위 생산에 100시간 노동이 필요하다고 가정하면 2번째 단위 생산에서는 80시간이 필요하고, 4번째 단위 생산에서는 64시간이 소요된다. 따라서 n번째 단위를 생산하는데 소요되는 시간은 첫 번째 단위 생산하는데 소요되는 시간과 지수함수 관계를 갖게 된다.

학습률에 따른 평균원가 변화 수식은 다음과 같다.

$$
Y_n = Y_1 \times n^R
$$

- $Y_n$: n번째 생산에 소요되는 공수
- $Y_1$: 첫 번째 생산단위 공수
- n: n번째 시점 생산량
- R: $\frac{log^b}{log^2}$
- b: 학습률

| **구분** | **장점** | **단점** |
|---------|---------|---------|
| **비용 측면** | 반복 작업을 통해 시간과 자원 사용을 절감하여 비용 절감 | 초기 투자 시 많은 시간과 비용이 소요될 수 있음 |
| **생산성 측면** | 반복 작업으로 효율성을 극대화해 생산성 향상 | 일정 수준 이후 추가적인 효율 향상이 어렵거나 느려질 수 있음 |
| **경쟁력 측면** | 기술 향상으로 시장에서 경쟁력 확보 | 특정 작업에 대한 숙련도가 타 작업에 쉽게 적용되지 않아 과도한 의존성 발생 |  
: 학습곡선 효과의 장단점

학습곡선 효과는 **비용 절감, 생산성 향상, 경쟁력 강화** 등의 장점을 제공하지만, **초기 비용 부담, 기술 습득의 한계, 과도한 의존성** 등의 단점도 수반한다.

::: {.callout-important icon=false title="1호기 공수가 10시간일 때 학습률이 80%인 경우"}

| **누적 생산량** | **단위당 평균 노동시간(시간)** | **총 노동시간(시간)** |
|-----------------|------------------------------|--------------------|
| 1             | 10.00                        | 10.00            |
| 2             | 8.00                         | 16.00            |
| 4             | 6.40                         | 25.60            |
| 8             | 5.12                         | 40.96            |
: 학습곡선(러닝 커브) 예제  

- **학습률(Learning Rate)**  
  단위당 평균 노동시간이 누적 생산량이 2배가 될 때마다 일정 비율로 감소함  
  예제에서는 1단위에서 2단위로 생산할 때 노동시간이 80%로 감소(10.00 → 8.00)  
- **누적평균시간법**을 통해 평균 노동시간 및 총 노동시간을 구함  
- 생산량이 증가할수록 단위당 노동시간이 감소하는 **학습곡선 효과(Learning Curve Effect)**를 보여줌  
:::

학습곡선의 활용 사례
: 
- 제조업체: 대량 생산 시 초기에는 시간이 많이 걸리지만, 생산이 증가함에 따라 생산 시간과 비용을 절감하는 데 활용
- 서비스 산업: 고객 서비스나 유지보수 작업에서 반복적으로 일을 처리하면서 효율성을 증가시키는 데 사용
- 기술 개발: 새로운 기술이나 시스템을 배울 때 학습곡선을 분석하여 개발 속도나 비용 절감을 예측

학습곡선 제약
: 
- 학습률은 기업, 작업 형태, 작업자에 따라 상이하므로 실증조사가 필요
- 시간추정치는 첫 단위 생산시간에 크게 의존하므로 이의 결정에 신중을 기해야 함
- 노동집약적 산업에 유효
- 다품종 소량생산에는 불리
