---
title: 2. 생산운영 및 물류관리
format: html
description: 생상관리 관련 주요 내용을 정리한다.
keywords: 수요예측과 일정계획, 프로세스 진도관리, 공급망 관리(SCM), 물류관리, 자재 및 재고관리
---

## 수요예측과 일정계획

### MRP vs APS

MRP(Material REquirements Planning)는 재고/자재 소요 계획 중심의 전통적인 물자소요계획 시스템인 반면, APS(Advanced Planning & Scheduing)는 자재와 생산능력까지 고려한 고도화된 생산계획 및 일정관리 시스템이다. 목적에 있어 전자가 생산 및 구매 자재 요구를 적시에 충족시키는 것이라면 
후자는 자재는 물론 설비와 인원 같은 유한 용량 조건까지 고려하여 최적 계획을 수립하는 것이다.

#### 계획 방식

**MPS**

- BOM 기반 하향식 물자 소요 계산
- 시스템은 용량을 무제한(무한, infinite capacity)으로 가정

**APS**

- 상위 수요 기반 계획
- 유한 용량(finite capacity) 고려, 일정 실행 가능 여부 사전 확인
- 경로 가시화, 페깅, 지연 예측 기능 포함

#### 기능 비교 요약

| 기능      | MRP    | APS                           |
| ------- | ------ | ----------------------------- |
| 용량 제약   | 무제한 가정 | 유한 용량 고려                      |
| 시뮬레이션   | 없음     | 다양한 시나리오 시뮬레이션 가능             |
| 경보 및 예측 | 제한적    | 지연 발생 시 경고, 페깅, 대체 가능 여부 제공   |
| 우선순위    | 물량 우선  | 고객 주문 우선 • 수익성 우선 등 우선 관리 가능  |


#### 장점과 단점

| 구분      | 장점                                                                         | 단점                                                     |
| ------- | -------------------------------------------------------------------------- | ------------------------------------------------------ |
| **MRP** | - 단순하고 저비용 시스템<br>- 예측 가능한 품목이 많을 때 적합                                | - 실질적인 생산 가능성 확인 불가 (capacity 무시)<br>- 비현실적인 일정 산출 경향  |
| **APS** | - 현실적인 일정 계획으로 OTD 향상<br>- 자재·용량·우선순위 통합 고려<br>- “What-if” 분석으로 유연 대응력 강화  | - 시스템 복잡도 및 고비용 부담<br>- 관리자 훈련 필요, 고품질 데이터 요구          |

MPS는 단순하고 비용 효율적인 자재 소요 계획에 적합하지만, 유한 용량을 고려하지 않기 때문에 실제 생산 실행 가능성에 한계가 있다. APS는 자재 뿐만 아니라 설비와 인력 등 유한 자원을 함게 고려해 현실적인 계획을 수립할 수 있으며, What-if 분석을 통해 생산 환경 변화에 능동적으로 대응할 수 있다. 다만 APS는 높은 시스템 복잡성, 투자 비용 그리고 운영 역량(관리자 및 데이터 인프라)이 요구된다.

## 프로세스 진도관리


## 공급망 관리(SCM)


## 물류관리(자재 및 재고관리)

### 채찍효과 

채찍효과(Bullwhip Effect)는 공급망에서 최종 소비자의 작은 수요변화가 상위 단계로 갈수록 점점 더 크게 증폭되는 현장을 의미한다. 마치 채찍 끝이 손목 움직임보다 훨씬 빠르고 크게 움직이는 것처럼 리테일 → 유통 → 제조로 데이터가 전달될수록 불확실성, 폭증이 커지게 된다.

- 소비자 수요 변화가 100 → 110건으로 증가할 경우,
	- 유통업체에서는 120건,
	- 도매업체에서는 150건
	- 제조사에서는 150건 주문 발생

#### 주요 원인

1. 수요 예측의 개별적 업데이트
	- 각 계측이 안전 재고 확보를 위해 예측 재고를 더 주문
2. 발주 배치화
	- 비용 절감을 위해 주문을 몰아서 하고, 이로 인해 수요 패터이 강조됨
3. 가격 변동 및 프로모션 영향
	- 할인, 행사 시 대량 주문, 행사 후 수요 급감 → 왜곡된 신호 발생
4. 정보 공유 부족 미 리드타임 지연
	- 상이한 시스템, 전산 지영ㄴ 등으로 인해 최신 수요 정보 공유가 늦어짐
5. 배급 게임
	- 재고 부족 시 과다 주문 유도, 반환 등으로 왜곡된 자료 생성

#### 주요 영향

- 과인 안전쟂고로 비용 증가, 창고 공간 부족, 자본 회전 저하
- 잘못된 생산 계획으로 설비 비효율, 납기 지연, 고객 서비스 저하
- 재고 과잉 또는 품절반복으로 수익 감소, 폐기 리스크, 직원 과인 채용, 해고 등 부정적 효과

#### 대응 방안  

| 전략                    | 설명                                    |
| --------------------- | ------------------------------------- |
| **정보 공유 강화**          | POS 데이터 실시간 공유, EDI 시스템 도입 통해 투명성 확보  |
| **발주 빈도 증가 & 배치 최소화** | 소량·빈번 주문으로 변동성 완화                     |
| **리드타임 단축**           | 제조·물류 효율화로 정보 지연 감소                   |
| **가격 정책 안정화**         | 할인·프로모션 구조 조정으로 부정적 주문 억제             |
| **계획 수요 중심 전환**       | JIT, VMI, 수요 기반 공급망(Demand-driven) 적용 |
| **전략적 협업 및 파트너십 강화**  | 공급망 참여자 간 협력 및 신뢰 구축                  |





*\_EOD\_*


