project:
  type: book
  output-dir: docs

book:
  title: "공장관리기술사(2E)"
  author: "YK"
  date: last-modified
  repo-url: https://github.com/yeonkyupark/pepc2e 
  repo-branch: main
  repo-actions: [edit]
  favicon: logo.png
  page-footer: 
    left: "Copyright 2025 YK" 
    right: 
      - icon: globe
        href: https://yeonkyupark.github.io/
  sidebar: 
    collapse-level: 1
    tools:
      - icon: globe
        href: https://yeonkyupark.github.io/
      - icon: instagram
        href: https://www.instagram.com/yeonkyu.park/
  chapters:
    - index.qmd
    - part: "01. 생산전략"
      chapters:
      - 0101경쟁우위생산전략.qmd
      - 0102생산구조와방식.qmd
      - 0103구매와외주전략.qmd
      - 0104인력과직무설계.qmd
      - 0105사업환경분석.qmd
    - part: "02. 생산운영"
      chapters:
      - 0201수요예측.qmd
      - 0202프로세스진도관리.qmd
    - part: "03. 물류관리"
      chapters:
      - 0301공급망관리.qmd
      - 0302물류관리.qmd
    - part: "04. 재고관리"
      chapters:
      - 0401재고관리.qmd
    - part: "05. 공정관리"
      chapters:
      - 0501생산계획수립.qmd
      - 0502공정설계.qmd
      - 0503작업계획수립.qmd
      - 0504표준작업관리.qmd
      - 0505공정개선.qmd
    - part: "06. 설비관리"
      chapters:
      - 0601설비계획.qmd
      - 0602설비보전관리.qmd
      - 0603자재취급및운반관리.qmd
      - 0604환경관리및안전관리.qmd
      - 0605시설및유틸리티관리.qmd
      - 0606공장자동화기술.qmd
    - part: "07. 작업관리"
      chapters:
      - 0701작업방법및시간연구.qmd
    - part: "08. 생산성관리"
      chapters:
      - 0801프로세스분석과개선.qmd
      - 0802생산성관리.qmd
      - 0803품질관리.qmd
    - part: "09. 원가관리"
      chapters:
      - 0901사업성분석.qmd
      - 0902원가관리.qmd
    - part: "10. 경제성 공학"
      chapters:
      - 1001가치공학.qmd
      - 1002경영과학.qmd
    - part: "11. 생산지원기술"
      chapters:
      - 1101정보화활용기술.qmd
      - 1102제품개발기술.qmd
      - 1103서비스운영관리.qmd
      - 1104생산혁신기술.qmd
      - 1105신기술및동향.qmd
    - part: "12. ISO"
      chapters:
      - 1201ISO9001.qmd
      - 1202ISO14001.qmd
      - 1203ISO31000.qmd
      - 1204ISO21500.qmd
    
bibliography: references.bib

number-sections: false

format:
  html:
    toc: true
    toc-depth: 4
    toc-title: 목차
    page-layout: full
    grid:
      body-width: 900px
    theme: 
      - lumen
      - custom.scss
    mermaid:
      theme: neutral

execute:
  freeze: auto

crossref:
  fig-title: 그림
  tbl-title: 표
  exm-title: 예제
  def-title: 정의
  def-prefix: "정의:"
  title-delim: " "
