---
description: 공장관리기술사는 공장관리 분야와 생산운영에 있어 전문지식과 실무경험을 갖추고 기술업무를 수행하는 직무이다.
---

<!-- google search console [[ -->
<meta name="google-site-verification" content="8xHzi-r2KaeozfPyDbwq2rtYE8sEI8Xu6irhM0ccwBU" />
<!-- google search console ]] -->

# 00. 들어가는 글 {.unnumbered}

## 공장관리기술사

**공장관리기술사**(Professional Engineer Plant Control)는 공장관리분야에 관한 고도의 전문 지식과 실무경험에 입각한 계획, 연구, 설계, 분석, 시험, 운영, 평가 또는 이에 관한 지도 등의 기술업무를 수행하는 직무이다. [^pepc]

[^pepc]: [https://www.q-net.or.kr/crf005.do?id=crf00503&jmCd=0760&gSite=Q&gId=](https://www.q-net.or.kr/crf005.do?id=crf00503&jmCd=0760&gSite=Q&gId=){target="_blank"}

필기 과목으로는 공장계획 및 설계, 공장조직, 생산계획 및 통제(공정관리), 설비 및 공구관리, 자재 및 운반관리, 작업관리, 경제성공학, 원가관리, 계기관리와 오퍼레이션리서치, 그 밖의 공장 관리에 관한 사항을 정의한다.

**주요항목**은 다음과 같다.[^출제기준]

1. 생산전략
1. 생산운영 및 물류관리
1. 공정관리
1. 설비관리
1. 작업 및 생산성과 측정과 개선
1. 원가관리 및 경제성 공학
1. 생산지원기술 및 기타

[^출제기준]: [https://www.q-net.or.kr/cst006.do?id=cst00601&code=1202&gSite=Q&gId=#](https://www.q-net.or.kr/cst006.do?id=cst00601&code=1202&gSite=Q&gId=#){target="_blank"}에서 공장관리기술사 검색

필기 시험을 합격하면 구술형 면접을 진행하게 되며 기술사로서 품위 및 자질 항목이 추가된다. 필기 및 면접 시험을 100점 만점 기준 60점 이상이면 합격이다.

본 자료는 공장관리기술사를 준비하면서 기출문제를 중심으로 관련 내용을 수집, 정리했다. 시중에 관련 서적이나 교재가 부족한 상황으로 시험 준비에 조금이나마 도움이 되었으면 한다. 다만 시험범위가 넓고 다양한 정답이 있을 수 있다는 점을 감안하여 참고하기 바란다. 공장관리기술사를 준비하거나 공장운영에 참고할 수 있는 체계적인 교과서가 만들어지길 바라본다.

## 글 구성

본 글은 공장관리기술사 주요 항목 순서에 따라 구성되며 상세항목 및 기타 관련 자료를 포함한다. 학습 편의를 위해 기출문제, 예제, 보충자료 등 다음과 같이 작성된다.

:::{.callout-caution icon=false title="목차 구성"}

목차 구성은 아래와 같으며, 세부항목은 필기 과목 주요항목별 상세 내용이다.

# 세부항목 {.unlisted}

## 세부항목별 주요 내용 {.unlisted}

### 세부항목별 상세 내용 {.unlisted}

#### 세부항목별 상세 내용 하위 {.unlisted}
:::

공장관리기술사 **기출 문제**는 아래와 같이 명시한다.  

> :::{.callout-tip icon=false title="기출: 회차-교시-문제번호"}
:::


공장관리기술사 대비 **예제** 문제는 아래와 같이 명시한다.

> :::{.callout-important icon=false title="예제"}
문제 및 풀이
:::

보충설명, 참고사항, 관련 용어 등 **참고자료**는 아래와 같이 명시한다.

> :::{.callout-note icon=false title="보충설명"}
용어 해설, 관련 설명
:::
